CREATE PROCEDURE sp_clear_batch_table
AS
BEGIN
    DECLARE @ThresholdYears INT;

    DELETE FROM IPASSPORTDDB.dbo.BATCH_JOB_EXECUTION;
    DELETE FROM IPASSPORTDDB.dbo.BATCH_JOB_EXECUTION_CONTEXT;
    DELETE FROM IPASSPORTDDB.dbo.BATCH_JOB_EXECUTION_PARAMS;
    DELETE FROM IPASSPORTDDB.dbo.BATCH_JOB_INSTANCE;
    DELETE FROM IPASSPORTDDB.dbo.BATCH_STEP_EXECUTION;
    DELETE FROM IPASSPORTDDB.dbo.BATCH_STEP_EXECUTION_CONTEXT;

END;
GO