CREATE PROCEDURE sp_clear_batch_table AS
BEGIN
    -- Start transaction
    BEGIN TRANSACTION;

    -- Delete from child tables first to maintain referential integrity
    DELETE FROM BATCH_STEP_EXECUTION_CONTEXT;
    DELETE FROM BATCH_JOB_EXECUTION_CONTEXT;
    DELETE FROM BATCH_STEP_EXECUTION;
    DELETE FROM BATCH_JOB_EXECUTION_PARAMS;
    DELETE FROM BATCH_JOB_EXECUTION;
    DELETE FROM BATCH_JOB_INSTANCE;

    -- Commit transaction
    COMMIT TRANSACTION;

END;